// Copyright 2022 CYBERCRYPT
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by copy-client.sh. DO NOT EDIT.
// version: v2.0.0-ci.67
// source: https://github.com/cybercryptio/d1-service-generic.git
// commit: 75a3140090e05b8c5736b031f09927e499587d9b

package client

import (
	pb "github.com/cybercryptio/d1-client-go/v2/d1-generic/protobuf/generic"
)

// GenericClient can be used to make calls to a D1 Generic service.
type GenericClient struct {
	BaseClient
	Generic pb.GenericClient
}

// NewGenericClient creates a new client for the given endpoint, configured with the provided options.
func NewGenericClient(endpoint string, opts ...Option) (GenericClient, error) {
	base, err := NewBaseClient(endpoint, opts...)
	if err != nil {
		return GenericClient{}, nil
	}

	return GenericClient{
		BaseClient: base,
		Generic:    pb.NewGenericClient(base.Connection),
	}, nil
}
