// Copyright 2022 CYBERCRYPT
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by copy-client.sh. DO NOT EDIT.
// version: v2.0.0-ci.17
// source: https://github.com/cybercryptio/d1-service-storage.git
// commit: aa07008b09a2f5c2fd5be0fe11a0aee00314bfe5

//go:build !skipexamples
// +build !skipexamples

package client_test

import (
	"context"
	"fmt"
	"log"

	"google.golang.org/grpc"

	gclient "github.com/cybercryptio/d1-client-go/v2/d1-generic"
	client "github.com/cybercryptio/d1-client-go/v2/d1-storage"
	pbstorage "github.com/cybercryptio/d1-client-go/v2/d1-storage/protobuf/storage"
)

func Example_withPerRPCCredentials() {
	// Create a new D1 Storage client providing the hostname, and optionally, the client connection level and per RPC credentials.
	client, err := client.NewStorageClient(endpoint,
		gclient.WithGrpcOption(grpc.WithTransportCredentials(creds)),
		gclient.WithTokenRefresh(uid, password),
	)
	if err != nil {
		log.Fatal(err)
	}

	ctx := context.Background()

	// Store sensitive data in encrypted form.
	storeResponse, err := client.Storage.Store(
		ctx,
		&pbstorage.StoreRequest{
			Plaintext:      []byte("secret data"),
			AssociatedData: []byte("metadata"),
		},
	)
	if err != nil {
		log.Fatal(err)
	}

	// Retrieve the stored data.
	retrieveResponse, err := client.Storage.Retrieve(
		ctx,
		&pbstorage.RetrieveRequest{
			ObjectId: storeResponse.ObjectId,
		},
	)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("plaintext:%q associated_data:%q",
		retrieveResponse.Plaintext,
		retrieveResponse.AssociatedData,
	)
	// Output: plaintext:"secret data" associated_data:"metadata"
}
