// Copyright 2022 CYBERCRYPT
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by copy-client.sh. DO NOT EDIT.
// version: v2.0.0
// source: https://github.com/cybercryptio/d1-service-storage.git
// commit: dca12031d22b45ef87a1df542069d95e65d08e12

package client

import (
	gclient "github.com/cybercryptio/d1-client-go/v2/d1-generic"
	pb "github.com/cybercryptio/d1-client-go/v2/d1-storage/protobuf/storage"
)

// GenericClient can be used to make calls to a D1 Storage service.
type StorageClient struct {
	gclient.BaseClient
	Storage pb.StorageClient
}

// NewStorageClient creates a new client for the given endpoint, configured with the provided options.
func NewStorageClient(endpoint string, opts ...gclient.Option) (StorageClient, error) {
	base, err := gclient.NewBaseClient(endpoint, opts...)
	if err != nil {
		return StorageClient{}, nil
	}

	return StorageClient{
		BaseClient: base,
		Storage:    pb.NewStorageClient(base.Connection),
	}, nil
}
