// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SearchableClient is the client API for Searchable service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchableClient interface {
	// Adds keywords/identifier pairs to secure index.
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	// Searches in secure index.
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// Deletes keywords/identifier pairs from secure index.
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type searchableClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchableClient(cc grpc.ClientConnInterface) SearchableClient {
	return &searchableClient{cc}
}

func (c *searchableClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, "/d1.Searchable/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchableClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/d1.Searchable/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchableClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/d1.Searchable/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchableServer is the server API for Searchable service.
// All implementations must embed UnimplementedSearchableServer
// for forward compatibility
type SearchableServer interface {
	// Adds keywords/identifier pairs to secure index.
	Add(context.Context, *AddRequest) (*AddResponse, error)
	// Searches in secure index.
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// Deletes keywords/identifier pairs from secure index.
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	mustEmbedUnimplementedSearchableServer()
}

// UnimplementedSearchableServer must be embedded to have forward compatible implementations.
type UnimplementedSearchableServer struct {
}

func (UnimplementedSearchableServer) Add(context.Context, *AddRequest) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedSearchableServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedSearchableServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSearchableServer) mustEmbedUnimplementedSearchableServer() {}

// UnsafeSearchableServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchableServer will
// result in compilation errors.
type UnsafeSearchableServer interface {
	mustEmbedUnimplementedSearchableServer()
}

func RegisterSearchableServer(s grpc.ServiceRegistrar, srv SearchableServer) {
	s.RegisterService(&Searchable_ServiceDesc, srv)
}

func _Searchable_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchableServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/d1.Searchable/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchableServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Searchable_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchableServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/d1.Searchable/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchableServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Searchable_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchableServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/d1.Searchable/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchableServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Searchable_ServiceDesc is the grpc.ServiceDesc for Searchable service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Searchable_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "d1.Searchable",
	HandlerType: (*SearchableServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Searchable_Add_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _Searchable_Search_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Searchable_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "searchable.proto",
}
